export const tracks = [
  {
    id: "solfeggio-852hz",
    name: "Solfeggio 852Hz",
    description:
      "High intensity wave to immediately reset your brain from almost everything",
    category: "solfeggio",
    popular: true,
    generator: "plain-frequency",
    frequency: 852,
    toneLevel: 0.5,
  },
  {
    id: "arousal-decrease",
    name: "Arousal Decrease",
    description:
      "Low complexity wave for stepping down from sexual overstimulation",
    category: "downshift",
    popular: true,
    generator: "breath-pulse-tone-v2",
    baseFrequency: 128,
    breathRateHz: 0.1,
    inhaleRatio: 0.42,
    modulationDepth: 0.32,
    toneLevel: 0.07,
    noiseLevel: 0.035,
    noiseColor: "brown",
    lowpassHz: 1000,
    stereoWidth: 0.25,
  },
  {
    id: "stim-reset",
    name: "Stimulation Reset",
    description:
      "Very simple low tone for resetting after scrolling, gaming, or high stimulation activity",
    category: "downshift",
    popular: true,
    generator: "breath-pulse-tone-v2",
    baseFrequency: 110,
    breathRateHz: 0.085,
    inhaleRatio: 0.38,
    modulationDepth: 0.36,
    toneLevel: 0.065,
    noiseLevel: 0.04,
    noiseColor: "brown",
    lowpassHz: 850,
    stereoWidth: 0.22,
  },
  {
    id: "stress-release",
    name: "Stress Release",
    description:
      "Slow movement wave for decompression after demanding work or social load",
    category: "relaxation",
    popular: true,
    generator: "nature-noise",
    scene: "ocean",
    intensity: 0.46,
    airLevel: 0.05,
    lowpassHz: 1000,
    highpassHz: 35,
    waveRateHz: 0.065,
    stereoWidth: 0.5,
  },
  {
    id: "anxiety-release",
    name: "Anxiety Release",
    description: "Soft brown noise for reducing perceived urgency",
    category: "downshift",
    popular: true,
    generator: "breath-pulse-tone-v2",
    baseFrequency: 96,
    breathRateHz: 0.08,
    inhaleRatio: 0.36,
    modulationDepth: 0.42,
    toneLevel: 0.07,
    noiseLevel: 0.045,
    noiseColor: "brown",
    lowpassHz: 760,
    stereoWidth: 0.28,
  },
  {
    id: "deep-work",
    name: "Deep Work",
    description:
      "Very slow motion for long coding, writing, or thinking sessions",
    category: "focus",
    popular: true,
    generator: "harmonic-cloud",
    baseFrequency: 196,
    partials: [
      { ratio: 1, type: "sine", gain: 0.08, pan: 0 },
      { ratio: 1.5, type: "sine", gain: 0.035, detuneCents: 2, pan: -0.15 },
      { ratio: 2, type: "triangle", gain: 0.018, detuneCents: -3, pan: 0.15 },
    ],
    driftFrequency: 0.006,
    driftDepthCents: 3,
    shimmerLevel: 0.004,
    shimmerBandHz: 2400,
    filterCutoffHz: 1800,
    stereoWidth: 0.2,
  },
  {
    id: "stop-procrastinating",
    name: "Stop Procrastionating",
    description:
      "Clean light movement for task initiation and steady execution",
    category: "focus",
    generator: "harmonic-cloud",
    baseFrequency: 185,
    partials: [
      { ratio: 1, type: "sine", gain: 0.075, pan: 0 },
      { ratio: 1.333, type: "sine", gain: 0.034, detuneCents: 2, pan: -0.16 },
      { ratio: 2, type: "triangle", gain: 0.022, detuneCents: -2, pan: 0.16 },
    ],
    driftFrequency: 0.012,
    driftDepthCents: 5,
    shimmerLevel: 0.008,
    shimmerBandHz: 2200,
    filterCutoffHz: 2200,
    stereoWidth: 0.3,
  },
  {
    id: "gaming-focus",
    name: "Gaming Focus",
    description: "Very ow level rhythmic tone to support alertness",
    category: "focus",
    generator: "isochronic-tone",
    baseFrequency: 200,
    beatFrequency: 16,
    dutyCycle: 0.48,
    modulationDepth: 0.24,
    toneLevel: 0.026,
    clickSmoothingMs: 24,
    noiseLevel: 0.014,
    lowpassHz: 2200,
  },
  {
    id: "nervous-system-settle",
    name: "Nervous System Settle",
    description: "Brown noise for a stable, low-detail background",
    category: "downshift",
    generator: "colored-noise-bed",
    noiseColor: "brown",
    noiseLevel: 0.052,
    lowpassHz: 800,
    highpassHz: 35,
    modulationFrequency: 0.01,
    modulationDepth: 0.06,
    stereoWidth: 0.25,
    filterDriftHz: 0.004,
  },
  {
    id: "study-retention",
    name: "Study Track",
    description: "Low harmonic stability for longer study blocks",
    category: "study",
    generator: "harmonic-cloud",
    baseFrequency: 174,
    partials: [
      { ratio: 1, type: "sine", gain: 0.072, pan: 0 },
      { ratio: 1.25, type: "sine", gain: 0.028, detuneCents: 2, pan: -0.12 },
      { ratio: 1.5, type: "triangle", gain: 0.024, detuneCents: -2, pan: 0.12 },
      { ratio: 2, type: "sine", gain: 0.016, detuneCents: 1, pan: 0 },
    ],
    driftFrequency: 0.007,
    driftDepthCents: 4,
    shimmerLevel: 0.005,
    shimmerBandHz: 2000,
    filterCutoffHz: 1900,
    stereoWidth: 0.22,
  },
  {
    id: "attention-mask",
    name: "Attention Mask",
    description:
      "Moderate filtered noise for masking office, traffic, cafe, or household distractions",
    category: "focus",
    generator: "colored-noise-bed",
    noiseColor: "pink",
    noiseLevel: 0.045,
    lowpassHz: 3600,
    highpassHz: 70,
    modulationFrequency: 0.012,
    modulationDepth: 0.08,
    stereoWidth: 0.35,
    filterDriftHz: 0.006,
  },
  {
    id: "low-stress-work",
    name: "Low Stress Work",
    description: "Soft warm noise for easy productive flow",
    category: "easeful-work",
    generator: "harmonic-cloud",
    baseFrequency: 146.83,
    partials: [
      { ratio: 1, type: "sine", gain: 0.068, pan: 0 },
      { ratio: 1.5, type: "sine", gain: 0.03, detuneCents: 2, pan: -0.2 },
      { ratio: 2, type: "triangle", gain: 0.018, detuneCents: -2, pan: 0.2 },
    ],
    driftFrequency: 0.011,
    driftDepthCents: 5,
    shimmerLevel: 0.006,
    shimmerBandHz: 1800,
    filterCutoffHz: 1700,
    stereoWidth: 0.28,
  },
  {
    id: "post-work",
    name: "Post Work",
    description: "Short downshift noise after tiring work",
    category: "reset",
    generator: "breath-pulse-tone-v2",
    baseFrequency: 128,
    breathRateHz: 0.095,
    inhaleRatio: 0.4,
    modulationDepth: 0.34,
    toneLevel: 0.066,
    noiseLevel: 0.028,
    noiseColor: "brown",
    lowpassHz: 950,
    stereoWidth: 0.2,
  },
  {
    id: "soft-rain-calm",
    name: "Soft Rain Calm",
    description:
      "Procedural low-density rain texture for relaxed background listening",
    category: "relaxation",
    popular: true,
    generator: "nature-noise",
    scene: "rain",
    intensity: 0.38,
    airLevel: 0.045,
    lowpassHz: 2400,
    highpassHz: 120,
    dropletDensity: 0.42,
    stereoWidth: 0.45,
  },
  {
    id: "open-awareness",
    name: "Open Awareness",
    description: "Spacious light noise for increase awareness",
    category: "meditation",
    generator: "harmonic-cloud",
    baseFrequency: 123.47,
    partials: [
      { ratio: 1, type: "sine", gain: 0.058, pan: 0 },
      { ratio: 1.5, type: "sine", gain: 0.024, detuneCents: 2, pan: -0.25 },
      { ratio: 2.5, type: "triangle", gain: 0.012, detuneCents: -3, pan: 0.25 },
    ],
    driftFrequency: 0.009,
    driftDepthCents: 6,
    shimmerLevel: 0.012,
    shimmerBandHz: 3000,
    filterCutoffHz: 2400,
    stereoWidth: 0.45,
  },
  {
    id: "solfeggio-396hz",
    name: "Solfeggio 396Hz",
    description: "Plain 396 Hz sine tone from Solfeggio's collection",
    category: "solfeggio",
    generator: "plain-frequency",
    frequency: 396,
    toneLevel: 0.45,
  },
  {
    id: "solfeggio-417hz",
    name: "Solfeggio 417Hz",
    description: "Plain 417 Hz sine tone from Solfeggio's collection",
    category: "solfeggio",
    generator: "plain-frequency",
    frequency: 417,
    toneLevel: 0.45,
  },
  {
    id: "solfeggio-528hz",
    name: "Solfeggio 528Hz",
    description: "Plain 528 Hz sine tone from Solfeggio's collection",
    category: "solfeggio",
    generator: "plain-frequency",
    frequency: 528,
    toneLevel: 0.042,
  },
  {
    id: "solfeggio-639hz",
    name: "Solfeggio 639Hz",
    description: "Plain 639 Hz sine tone from Solfeggio's collection",
    category: "solfeggio",
    generator: "plain-frequency",
    frequency: 639,
    toneLevel: 0.4,
  },
  {
    id: "solfeggio-741hz",
    name: "Solfeggio 741Hz",
    description: "Plain 741 Hz sine tone from Solfeggio's collection",
    category: "solfeggio",
    generator: "plain-frequency",
    frequency: 741,
    toneLevel: 0.38,
  },
  {
    id: "sleep-noise",
    name: "Sleep Noise",
    description: "Low brown noise with subtle movement for sleep",
    category: "sleep",
    popular: true,
    generator: "sleep-slow-wave",
    baseFrequency: 96,
    toneLevel: 0.025,
    noiseColor: "brown",
    noiseLevel: 0.055,
    slowPulseHz: 0.85,
    pulseDepth: 0.06,
    lowpassHz: 650,
    stereoWidth: 0.25,
  },
  {
    id: "alpha-focus-experimental",
    name: "Alpha Focus Experimental",
    description:
      "Headphone only alpha binaural beat for optional focus experimentation",
    category: "experimental",
    generator: "binaural-beat",
    carrierFrequency: 200,
    beatFrequency: 10,
    toneLevel: 0.035,
    noiseLevel: 0.018,
    noiseColor: "pink",
    lowpassHz: 1800,
    headphoneOnly: true,
    rampSeconds: 8,
  },
  {
    id: "theta-wind-down-experimental",
    name: "Theta Noise Experimental",
    description:
      "Headphone-only low-level theta binaural beat for evening relaxation experiments",
    category: "experimental",
    generator: "binaural-beat",
    carrierFrequency: 180,
    beatFrequency: 6,
    toneLevel: 0.028,
    noiseLevel: 0.024,
    noiseColor: "brown",
    lowpassHz: 1200,
    headphoneOnly: true,
    rampSeconds: 10,
  },
  {
    id: "gamma-focus-experimental",
    name: "Gamma Focus Experimental",
    description:
      "Low level 40 Hz isochronic-style pulse for short optional focus experiments",
    category: "experimental",
    generator: "isochronic-tone",
    baseFrequency: 200,
    beatFrequency: 40,
    dutyCycle: 0.5,
    modulationDepth: 0.22,
    toneLevel: 0.025,
    clickSmoothingMs: 20,
    noiseLevel: 0.015,
    lowpassHz: 2200,
  },
];
